export const characters = [
  {
    id: "ch_01",
    name: "諾姆．霍洛維爾",
    name_en: "Norma",
    belong: "外務籌策局",
    b_img: "/characters/be_01.png",
    head: "/characters/chh_01.png",
    image: "/characters/ch_01.png",
    offsetX: "50%",
  },
  {
    id: "ch_02",
    name: "維琳娜．愛嘉德",
    name_en: "Velina",
    belong: "外務籌策局",
    b_img: "/characters/be_01.png",
    head: "/characters/chh_02.png",
    image: "/characters/ch_02.png",
    offsetX: "57%",
  },
  {
    id: "ch_03",
    name: "佩洛伊斯",
    name_en: "Pyrois",
    belong: "法厄同",
    b_img: "/characters/be_02.png",
    head: "/characters/chh_03.png",
    image: "/characters/ch_03.png",
    offsetX: "60%",
  },
  {
    id: "ch_04",
    name: "星徽．比利",
    name_en: "Starlight Billy",
    belong: "狡兔屋",
    b_img: "/characters/be_03.png",
    head: "/characters/chh_04.png",
    image: "/characters/ch_04.png",
    offsetX: "55%",
  },
  {
    id: "ch_05",
    name: "普羅米婭",
    name_en: "Promeia",
    belong: "坎卜斯黑枝",
    b_img: "/characters/be_04.png",
    head: "/characters/chh_05.png",
    image: "/characters/ch_05.png",
    offsetX: "55%",
  },
  {
    id: "ch_06",
    name: "希希芙",
    name_en: "Cissia",
    belong: "都市秩序部",
    b_img: "/characters/be_05.png",
    head: "/characters/chh_06.png",
    image: "/characters/ch_06.png",
    offsetX: "55%",
  },
  {
    id: "ch_07",
    name: "南宮羽",
    name_en: "Nangong Yu",
    belong: "妄想天使",
    b_img: "/characters/be_06.png",
    head: "/characters/chh_07.png",
    image: "/characters/ch_07.png",
    offsetX: "55%",
  },
  {
    id: "ch_08",
    name: "愛芮",
    name_en: "Aria",
    belong: "妄想天使",
    b_img: "/characters/be_06.png",
    head: "/characters/chh_08.png",
    image: "/characters/ch_08.png",
    offsetX: "55%",
  },
  {
    id: "ch_09",
    name: "千夏",
    name_en: "Sunna",
    belong: "妄想天使",
    b_img: "/characters/be_06.png",
    head: "/characters/chh_09.png",
    image: "/characters/ch_09.png",
    offsetX: "55%",
  },
];
